# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ce5b4f7e6fa62bb595e6ed873de056b78c6588e5557699cf57dfeac002707f1c556261643a7a251c83c89e83d3e30199522c6473f43a66a7d7dd3326729278d

test:
  secret_key_base: 789e66a48c5e59cd8e5ad394838dd040cf52367fad2516ce4490d533705fc92768e285a9d9780272f95a68552eb97acf1385b10754f25a49d0013d29785ad0b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
